//
// Do not edit this file, it is autogenerated by the `site-meta` grunt task.
// See Gruntfile.js for more information.
//

import {CONST_EXPR, Type} from 'angular2/src/facade/lang';

// --=> EXAMPLES_IMPORT_START
import CardBasicUsage from './components/card/basic_usage';
import CardInlineActions from './components/card/inline_actions';
import ButtonBasicUsage from './components/button/basic_usage';
import CardActionButtons from './components/card/action_buttons';
import ToolbarBasicUsage from './components/toolbar/basic_usage';
import ToolbarScrollShrink from './components/toolbar/scroll_shrink';
import ProgressLinearBasicUsage from './components/progress_linear/basic_usage';
import RadioBasicUsage from './components/radio/basic_usage';
import SwitchBasicUsage from './components/switch/basic_usage';
import TabsBasicUsage from './components/tabs/basic_usage';
// --=> EXAMPLES_IMPORT_END

/**
 * Collection of Material Design component directives.
 */
export const DEMO_DIRECTIVES: Type[] = CONST_EXPR([
// --=> EXAMPLES_EXPORT_START
  CardBasicUsage, CardInlineActions, CardActionButtons,
  ButtonBasicUsage,
  RadioBasicUsage,
  SwitchBasicUsage,
  TabsBasicUsage,
  ToolbarBasicUsage, ToolbarScrollShrink,
  ProgressLinearBasicUsage
// --=> EXAMPLES_EXPORT_END
]);

export * from './example';
